# Generated by Django 5.0.1 on 2024-05-17 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('users', '0003_rename_name_usermodel_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Total price')),
                ('full_name', models.CharField(db_index=True, max_length=50, verbose_name='Full Name')),
                ('address_line1', models.CharField(db_index=True, max_length=250, verbose_name='Address Line1')),
                ('address_line2', models.CharField(db_index=True, max_length=250, verbose_name='Address Line2')),
                ('city', models.CharField(db_index=True, max_length=25, verbose_name='City')),
                ('state', models.CharField(db_index=True, max_length=25, verbose_name='State')),
                ('postal_code', models.IntegerField(db_index=True, verbose_name='Postal Code')),
                ('country', models.CharField(db_index=True, default='United State', max_length=25, verbose_name='Country')),
                ('telephone', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Telephone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_index=True, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'Order Item',
            },
        ),
    ]
