# Generated by Django 5.0.6 on 2024-05-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='Email')),
                ('password', models.CharField(db_index=True, max_length=100, verbose_name='password')),
                ('token', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='token')),
                ('token_expires_at', models.DateTimeField(auto_now=True, verbose_name='Token Expires DateTime')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated DateTime')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
